[config]
X11_path = "/mnt/wslg/.X11-unix"
mounts = [
    "vscode/.vscode-server/:$HOME/.vscode-server",
    "init_env.sh:/etc/profile.d/init_env.sh",
    "$HOME/.ssh:$HOME/.ssh",
    "cursor/.local:$HOME/.local",
    "cursor/.cursor:$HOME/.cursor",
    "cursor/.gnupg:$HOME/.gnupg",
    "cursor/.dotnet:$HOME/.dotnet",
    "cursor/.config:$HOME/.config",
    "verilator/share/verilator:/usr/share/verilator",
    "$HOME/repo:$HOME/repo",
]

[config.image]
name = "fabrinetes-fpga-full"
tag = "latest"
tarball_path = "fabrinetes-fpga-full-latest.tar.gz"

[config.base_image]
name = "fabrinetes-skeleton"
tag = "latest"
tarball_path = "fabrinetes-skeleton-latest.tar.gz"

[config.container]
name = "fpga-dev"
