[Containers.fabrinetes1]
REPOSITORY      = "fabrinetes-dev"
TAG             = "latest"
mounts          =["/home/ykarmon/AMD/Vivado/2021.2:/opt/vivado","/home/ykarmon/repos:/root/repos"]
PATH            =["/opt/vivado"]



