[config]
image_name       = "fabrinetes-dev-testing:latest"
base_image      = "fabrinetes-skeleton:latest"
X11_path             = "/mnt/wslg/.X11-unix"
mounts              = [
    "$HOME/.ssh:$HOME/.ssh",
    "$HOME/repo:$HOME/repo",
]
