[config]
# X11 and mount configuration
X11_path = "/mnt/wslg/.X11-unix:/tmp/.X11-unix"
mounts = [
    "$HOME/.ssh:$HOME/.ssh",
    "$HOME/repo:$HOME/repo",
    "$HOME/repo/Fabrinetes/source/project_setup:/opt/project_setup",
    "$HOME/.Xauthority:$HOME/.Xauthority:ro",
    "init_env.sh:/etc/profile.d/init_env.sh",
    "bashrc-root:$HOME/.bashrc",
    "cursor/.local:$HOME/.local",
    "cursor/.dotnet:$HOME/.dotnet",
    "cursor/.config:$HOME/.config",
    "cursor/.cursor:$HOME/.cursor",
    "cursor/.gnupg:$HOME/.gnupg",
    "verilator/share/verilator:/usr/share/verilator",
    "vscode/.vscode-server:$HOME/.vscode-server",
]

[config.base_image]
name = "fabrinetes-skeleton"
tag = "latest"
tarball_path = "fabrinetes-skeleton:latest.tar.gz"
dockerfile_path = "Dockerfile"
package_list_path = "packages.txt"


[config.image]
name = "fabrinetes-testing"
tag = "latest"
tarball_path = "fabrinetes-testing:latest.tar.gz"


[config.container]
name = "testing"
