#!/bin/bash

if [ -z "$REPO_TOP" ]; then
    echo "❌ REPO_TOP is not set. Please export REPO_TOP first."
    exit 1
fi

TASKS_DIR="/opt/project_setup"
shell_id="$PPID"
timestamp=$(date +%Y%m%d)
time=$(date +%H%M%S)

export HDLFORGE_ORIG_PATH="$(pwd)"
mkdir -p "$TASKS_DIR/logs"
log_file="$TASKS_DIR/logs/hdlforge_${timestamp}_pid${shell_id}.log"

# Change to the tasks directory before running invoke
cd "$TASKS_DIR" || {
    echo "❌ Failed to cd into $TASKS_DIR"
    echo "run update_repo_path correctly."
    exit 1
}

# If no arguments are passed, default to --list
if [ $# -eq 0 ]; then
    set -- --list
fi
echo "--------$(pwd): $Date: $timestamp Time $time------" >> "$log_file"
# Run invoke as if we were in that directory
exec invoke -c tasks "$@" | tee -a "$log_file"
