[config]
# Mount configuration
mounts = [
    "$HOME/.ssh:$HOME/.ssh",
    "$HOME/repo:$HOME/repo",
    "init_env.sh:/etc/profile.d/init_env.sh",
    "../../hdlforge/bashrc-root:$HOME/.bashrc"
]

[config.X11]
enable = true  # Enable X11 GUI support (defaults to true if not present)
mounts = [
    "/mnt/wslg/.X11-unix:/tmp/.X11-unix",  # X11 socket path
    "$HOME/.Xauthority:$HOME/.Xauthority:ro"  # X11 authentication
]

[config.image]
name = "ykarmon/fabrinetes"
tag = "v1.0"
dockerfile_path = "Dockerfile"
package_list_path = "packages.txt"


[config.container]
name = "fabrinetes-local-run"
