[config]
# X11 and mount configuration
X11_path = "/mnt/wslg/.X11-unix:/tmp/.X11-unix"
mounts = [
    "$HOME/.ssh:$HOME/.ssh",
    "$HOME/repo:$HOME/repo",
    "$HOME/.Xauthority:$HOME/.Xauthority:ro",
    "init_env.sh:/etc/profile.d/init_env.sh",
    "../../hdlforge/bashrc-root:$HOME/.bashrc"
]

[config.image]
name = "fabrinetes-local"
tag = "latest"
tarball_path = "fabrinetes-local:latest.tar.gz"
dockerfile_path = "Dockerfile"
package_list_path = "packages.txt"


[config.container]
name = "fabrinetes-local-run"
